const mongoose = require('mongoose');
const User = require('../users/user.model');
const Schema = mongoose.Schema;
const List = require("collections/list");
const { Int32 } = require('mongodb');

const ContentSchema = mongoose.Schema({
    //I assume _id is automatically generated by Mongo, otherwise add _id: Int32 
    //Data about the content 
    displayDate: { type: Date, default: Date.now},
    createdDate: { type: Date, default: Date.now},
    title: { type: String, required: true}, 
    description: { type: String}, 
    content:{ type: File}, 
    //Data for search/connecting 
    user: {type: String, required: true },
    //list of strings
    tags:{type: [{type:String}]}, 
    viewPermissions:{type: String, Enum: ["Public", "Private", "InviteOnly"] }
}); 

module.export = mongoose.model('Content', ContentSchema); 
