const mongoose = require('mongoose');
const User = db.User; 
const Schema = mongoose.Schema;
const List = require("collections/list");
const { Int32 } = require('mongodb');

const ContentSchema = mongoose.Schema({
    //I assume _id is automatically generated by Mongo, otherwise add _id: Int32 
    //Data about the content 
    displayDate: { type: Date, default: Date.now},
    createdDate: { type: Date, default: Date.now},
    title: { type: String, required: true}, 
    description: { type: String}, 
    content:{ type: File}, 
    //Data for search/connecting 
    user: {type: String, required: true },
    //list of strings
    tags:{type: [{type:String}]}, 
    viewPermissions:{type: String, Enum: ["Public", "Private", "InviteOnly"] }
}); 

//Sets the schema to a json doc? 
schema.set('toJSON', {
    virtuals: true,
    versionKey: false,
    transform: function (doc, ret) {
        //delete ret._id;
        delete ret.hash;
    }
});

module.export = mongoose.model('Content', ContentSchema); 
